### ISSUE TITLE
Still in development ? Alternatives ?

### ISSUE THREAD

**Issue by Eliepse** [SoftwareBrothers/better-docs#145]
Hi,
This project is really usefull, but is it still in development?
I started using it in my company but we encounter bugs that makes in useless...

If this project is not maintained any more, do you have any alternatives?

**Comment by futurGH** [comment]
Personally, I used better-docs primarily for its TypeScript support.

Since it does not seem to be maintained anymore, I used the TypeScript parsing code from this repo to develop **[ts-docmagen](https://www.npmjs.com/package/ts-docmagen)**, which generates documentation using a fork of the [Docma](https://github.com/onury/docma) documentation generator (which, ironically, also does not seem to be maintained anymore!)

If anyone else is looking for an alternative to better-docs that allows you to generate documentation that takes into account your TypeScript typings, be sure to take a look at **[ts-docmagen](https://www.npmjs.com/package/ts-docmagen)**!

**Comment by loganpowell** [comment]
@futurGH I'm looking at `ts-docmagen` and I'm happy that someone has picked up the torch (I am just tired of looking at npm vulnerabilities every time I generate docs), but it could use a bit more documentation. E.g., are there any example docs that you've generated with it that we can peruse?

**Comment by futurGH** [comment]
@loganpowell Thanks for taking a look! As I mentioned, it's built on top of another documentation generator,  [Docma](https://github.com/onury/docma). Really the only thing my package does is transpile the TypeScript code into compatible JSDoc comments for Docma to pick up and generate documentation from. It's worth noting that it's not perfect, but you can find an example of what the output docs might look like at [Docma's own API reference](https://onury.io/docma/api/https://onury.io/docma/api/).

**Comment by loganpowell** [comment]
Perfect, thank you @futurGH

**Comment by PuneetGopinath** [comment]
@futurGH Can you help me to set it up?
I still have problems, should I install both packages and run your package's command? If yes, that's done
Should I run docma's command also? If no, then I am done, but yet not working
It generates empty page

**Comment by lukasz-szramko-rst** [comment]
Yes it's still in development. Please check latest version `2.7.1`
